export * from "./EditProfile";
export * from "./Errorpage";
export * from "./Home";
export * from "./Login";
export * from "./NowPlaying";
export * from "./Profile";
export * from "./ResetPassword";
export * from "./SplashScreen";
export * from "./index";
