export const types = {
    GET_ALL_MUSIC:"GET_ALL_MUSIC", 
    CHANGE_PLAYON:"CHANGE_PLAYON",
    HANDLE_INDEX:"HANDLE_INDEX",
    TOGGLE_RANDOM:'TOGGLE_RANDOM',
    TOGGLE_REPEAT:'TOGGLE_OPTIONS',
    TOGGLE_PLAYING:'TOGGLE_PLAYING',
}
