export const types = {
  GET_ALL_MUSIC: "GET_ALL_MUSIC",
  HANDLE_INDEX: "HANDLE_INDEX",
  HANDLE_RANDOM: "HANDLE_RANDOM",
  HANDLE_REPEAT: "HANDLE_OPTIONS",
  ADD_PLAYLIST: "ADD_PLAYLIST",
  EDIT_PLAYLIST_TITLE: "EDIT_PLAYLIST_TITLE",
  EDIT_PLAYLIST_IMG: "EDIT_PLAYLIST_IMG",
  HANDLE_LIKELIST: "HANDLE_LIKELIST",
  HANDLE_PLAYLIST: "HANDLE_PLAYLIST",
  CHANGE_CURRENTLIST: "CHANGE_CURRENTLIST",
  PLAY_ACTIVE: "PLAY_ACTIVE",
  PLAY_DISABLED: "PLAY_DISABLED",
};
